#!/bin/sh

##################
### Basic shi ####
##################

# Open terminal
super + Return
	kitty

# Close focused window
super + q
	bspc node -c

# Switch workspaces 1-6
ctrl + {1-6}
    bspc desktop --focus {1-6}


####################
### Window stuff ###
####################

# Switch focus specifically
super + {h,j,k,l}
	bspc node -f {west,south,north,east}

# Focus next window (spam this 1 til desired effect)
super + z
    bspc node -f next.local

# Move focused window
super + shift + {h,j,k,l}
	bspc node -s {west,south,north,east}

# Swap positions w/ 2 windows open
super + s
        bspc node -s @brother.local
 
# Move focused window to desktop 1-6 (current monitor only)
ctrl + shift + {1-6}
    bspc node -d {1-6}

# Send window to other monitor and follow it
ctrl + shift + 0
    bspc node -m HDMI-A-0 --follow


##################
### Laptop shi ###
##################

# Volume Laptop Keys
XF86AudioRaiseVolume
    ~/.config/bspwm/scripts/volume.sh up

XF86AudioLowerVolume
    ~/.config/bspwm/scripts/volume.sh down

XF86AudioMute
    ~/.config/bspwm/scripts/volume.sh mute

# Brightness Laptop Keys
XF86MonBrightnessUp
    ~/.config/bspwm/scripts/brightness.sh up

XF86MonBrightnessDown
    ~/.config/bspwm/scripts/brightness.sh down

# Media Keys
XF86AudioPlay
    ~/.config/bspwm/scripts/media.sh play

XF86AudioNext
    ~/.config/bspwm/scripts/media.sh next

XF86AudioPrev
    ~/.config/bspwm/scripts/media.sh prev


#######################
### Program hotkeys ###
#######################

# Launch rofi
super + a
        ~/.config/rofi/launchers/type-3/launcher.sh

# Reload sxhkd
super + Escape
        pkill -USR1 -x sxhkd

# Quit bspwm
super + alt + q
        bspc quit
