#! /bin/sh

#             Roman's
#   _                                 
#  | |__  ___ _ ____      ___ __ ___  
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#  | |_) \__ \ |_) \ V  V /| | | | | |
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#             |_|                    
#

pgrep -x sxhkd > /dev/null || sxhkd &


# Set up workspaces (1-X)
bspc monitor DisplayPort-2  -d 1 2 3 4 5 6 
bspc monitor HDMI-A-0 -d 7 8 9 0


# Window details
bspc config border_width         1.80
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config initial_polarity second_child
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Sets up monitors
xrandr --output DisplayPort-2 --mode 1920x1080 --rate 165 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rate 60 --rotate left --left-of DisplayPort-2

# Sets up laptop
# xrandr --output eDP-1 

# Keep Discord/Vesktop on Workspace 4
bspc rule -a vesktop desktop="^6"

# Keep doom emacs on Workspace 1
bspc rule -a emacs desktop="^3"


# Autostart applications
sxhkd &
polybar top &
kitty -e zsh -c "neofetch; exec zsh" &
nitrogen --restore &
picom --config ~/.config/picom/picom.conf &
dunst &
flameshot &
solaar --window=hide &
mechvibes &
